config/routes.rb
Rails.application.routes.draw do
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/form/product.rb
class Form::Product < Product
  REGISTRABLE_ATTRIBUTES = %i[code name price]
  REGISTRABLE_RELATIONS = [category_ids: []]

  def selectable_categories
    Category.all
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories
  
  validates :code, presence: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Form::Product.new
  end

  def create
    @product = Form::Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprosessable_entity
    end
  end

  def edit
    @product = Form::Product.find(params[:id])
  end

  def update
    @product = Form::Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit, status: :unprosessable_entity
    end
  end

  private

  def product_params
    params
      .require(:form_product)
      .reverse_merge(category_ids: [])
      .permit(Form::Product::REGISTRABLE_ATTRIBUTES + Form::Product::REGISTRABLE_RELATIONS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="winter">
  <head>
    <title>FormObjectPracticeManyToManyCheckbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_with model: @product, url: products_path do |f| %>
  <div class="form-control w-full max-w-md">
    <%= f.label :code, class:'text-label' %>
    <%= f.text_field :code, class:'input input-bordered' %>
  </div>

  <div class="form-control w-full max-w-md">
    <%= f.label :name, class:'text-label' %>
    <%= f.text_field :name, class:'input input-bordered' %>
  </div>

  <div class="form-control w-full max-w-md">
    <%= f.label :price, class:'text-label' %>
    <%= f.number_field :price, class:'input input-bordered' %>
  </div>

  <div>
    <% f.object.selectable_categories.each do |category| %>
      <%= f.label :category_ids, value: category.id, class: 'checkbox' do %>
        <%= f.check_box :category_ids, { multiple: true }, category.id, nil %>
        <%= category.name %>
      <% end %>
    <% end %>
  </div>

  <%= f.submit '登録' ,class:'btn btn-prymary'%>
<% end %>

app/views/products/index.html.erb
<%= link_to '新規作成', new_product_path, class:'btn btn-primary' %>
<div class="overflow-x-auto">
  <table class="table w-full">
    <thead>
      <tr>
        <th>ID</th>
        <th>商品コード</th>
        <th>商品名</th>
        <th>販売価格</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.code %></td>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<%= form_with model: @product, url: products_path do |f| %>
  <div class="form-control w-full max-w-md">
    <%= f.label :code, class:'text-label' %>
    <%= f.text_field :code, class:'input input-bordered' %>
  </div>

  <div class="form-control w-full max-w-md">
    <%= f.label :name, class:'text-label' %>
    <%= f.text_field :name, class:'input input-bordered' %>
  </div>

  <div class="form-control w-full max-w-md">
    <%= f.label :price, class:'text-label' %>
    <%= f.number_field :price, class:'input input-bordered' %>
  </div>

  <div>
    <% f.object.selectable_categories.each do |category| %>
      <%= f.label :category_ids, value: category.id, class: 'checkbox' do %>
        <%= f.check_box :category_ids, { multiple: true }, category.id, nil %>
        <%= category.name %>
      <% end %>
    <% end %>
  </div>

  <%= f.submit '登録' ,class:'btn btn-prymary'%>
<% end %>